; Waveshare ESP32-S3-Knob-Touch-LCD-1.8 (target the S3 half)
[env:waveshare_knob_18_s3]
platform = espressif32
framework = arduino
board = esp32-s3-devkitc-1
board_build.flash_mode = qio
board_build.f_flash = 80000000L
board_build.arduino.memory_type = qio_opi
board_build.partitions = partitions_ota.csv
board_upload.flash_size = 16MB
build_flags =
  -DBOARD_HAS_PSRAM
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
monitor_speed = 115200
upload_speed = 921600
