#!/bin/sh
# Deploy the office ESP32-S3 thermo container over Jaguar WiFi (borgify).
set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ESP32_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
REPO="${REPO_PATH:-$(cd "$ESP32_DIR/../../../.." && pwd)}"
THERMO_ROOT="$REPO/thermo"
export THERMO_ROOT

log() { echo "[esp32s3-deploy] $*"; }

if [ ! -d "$REPO" ]; then
	log "Repo not found: $REPO. Set REPO_PATH."
	exit 1
fi

: "${THERMO_ENV_FILE:?set THERMO_ENV_FILE e.g. onboard/zones/office/zone.env}"

if [ "${1:-}" = "--preflight" ]; then
	log "preflight ok (Jaguar WiFi deploy; no serial flash in preflight)"
	exit 0
fi

if [ -f "$THERMO_ROOT/config/source-thermo-env.sh" ]; then
	set -a
	# shellcheck source=/dev/null
	. "$THERMO_ROOT/config/source-thermo-env.sh"
	set +a
fi

: "${ONBOARD_DEPLOY_BACKEND:?set ONBOARD_DEPLOY_BACKEND=esp32s3 in $THERMO_ENV_FILE}"
if [ "$ONBOARD_DEPLOY_BACKEND" != "esp32s3" ]; then
	echo "ONBOARD_DEPLOY_BACKEND=$ONBOARD_DEPLOY_BACKEND does not match esp32s3" >&2
	exit 1
fi

ESP32S3_PRIV_ENV="${ESP32S3_PRIV_ENV:-$THERMO_ROOT/priv/esp32s3/${ZONE_NAME:-office}.env}"
if [ -f "$ESP32S3_PRIV_ENV" ]; then
	set -a
	# shellcheck source=/dev/null
	. "$ESP32S3_PRIV_ENV"
	set +a
	log "loaded private ESP32-S3 env: $ESP32S3_PRIV_ENV"
fi

ESP32S3_JAGUAR_DEVICE_NAME="${ESP32S3_JAGUAR_DEVICE_NAME:-esp32s3-office}"
ESP32S3_JAGUAR_CONTAINER_NAME="${ESP32S3_JAGUAR_CONTAINER_NAME:-thermo-esp32s3}"
ESP32S3_JAGUAR_DEVICE="${ESP32S3_JAGUAR_DEVICE:-${ESP32S3_JAGUAR_DEVICE_ADDRESS:-$ESP32S3_JAGUAR_DEVICE_NAME}}"
ZONE_PRIVATE_KEY_PATH="${ZONE_PRIVATE_KEY_PATH:-$THERMO_ROOT/priv/zone/priv.pem}"

if ! command -v jag >/dev/null 2>&1; then
	log "jag not found; install with: brew install jaguar && jag setup"
	exit 1
fi

cd "$ESP32_DIR"

SECRETS_TOIT="$ESP32_DIR/src/secrets.toit"
PYTHON_BIN="${THERMO_ROOT}/onboard/.venv/bin/python"
if [ ! -x "$PYTHON_BIN" ]; then
	PYTHON_BIN=python3
fi
if [ ! -f "$ZONE_PRIVATE_KEY_PATH" ]; then
	log "zone private key not found: $ZONE_PRIVATE_KEY_PATH"
	exit 1
fi
log "generating gitignored src/secrets.toit from zone key"
"$PYTHON_BIN" - "$ZONE_PRIVATE_KEY_PATH" "$SECRETS_TOIT" "${DMZ_HOST:-jovlinger.duckdns.org}" "${DMZ_PORT:-5000}" "${ZONE_NAME:-office}" <<'PY'
import sys
from pathlib import Path

from cryptography.hazmat.primitives import serialization

key_path = Path(sys.argv[1])
out_path = Path(sys.argv[2])
dmz_host = sys.argv[3]
dmz_port = int(sys.argv[4])
zone_name = sys.argv[5]

key = serialization.load_pem_private_key(key_path.read_bytes(), password=None)
seed = key.private_bytes(
    encoding=serialization.Encoding.Raw,
    format=serialization.PrivateFormat.Raw,
    encryption_algorithm=serialization.NoEncryption(),
)

seed_bytes = ",".join(str(b) for b in seed)
out_path.write_text(
    "// Generated by install/deploy.sh. DO NOT COMMIT.\n"
    f'ZONE-SEED ::= #[{seed_bytes}]\n'
    f'DMZ-HOST ::= "{dmz_host}"\n'
    f"DMZ-PORT ::= {dmz_port}\n"
    f'DMZ-PATH ::= "/zone/{zone_name}/sensors"\n',
    encoding="ascii",
)
PY

log "selecting Jaguar device: $ESP32S3_JAGUAR_DEVICE"
if ! jag scan "$ESP32S3_JAGUAR_DEVICE" >/dev/null 2>&1; then
	log "device not found at $ESP32S3_JAGUAR_DEVICE; trying jag scan -l"
	ESP32S3_JAGUAR_DEVICE="$(jag scan -l 2>/dev/null | head -1 || true)"
	if [ -z "$ESP32S3_JAGUAR_DEVICE" ]; then
		log "no Jaguar device found on LAN"
		exit 1
	fi
	log "using first discovered device name: $ESP32S3_JAGUAR_DEVICE"
	jag scan "$ESP32S3_JAGUAR_DEVICE" >/dev/null
fi

current_name="$(jag scan -l 2>/dev/null | head -1 || true)"
if [ -n "$current_name" ] && [ "$current_name" != "$ESP32S3_JAGUAR_DEVICE_NAME" ]; then
	log "renaming device $current_name -> $ESP32S3_JAGUAR_DEVICE_NAME (OTA)"
	jag firmware update --name "$ESP32S3_JAGUAR_DEVICE_NAME" -d "$ESP32S3_JAGUAR_DEVICE"
	jag scan "$ESP32S3_JAGUAR_DEVICE_NAME" >/dev/null
	ESP32S3_JAGUAR_DEVICE="$ESP32S3_JAGUAR_DEVICE_NAME"
fi

log "borgifying container $ESP32S3_JAGUAR_CONTAINER_NAME from src/main.toit"
jag container install "$ESP32S3_JAGUAR_CONTAINER_NAME" src/main.toit -d "$ESP32S3_JAGUAR_DEVICE"

log "installed containers:"
jag container list -d "$ESP32S3_JAGUAR_DEVICE"
log "done"
