#!/usr/bin/env python3
"""Build utils/README.md from nested .www/blurb.md files."""

from __future__ import annotations

import sys
from pathlib import Path
from typing import Iterator, List, Optional, Sequence

UTILS_ROOT: Path = Path(__file__).resolve().parent.parent
README_PATH: Path = UTILS_ROOT / "README.md"
BLURB_NAME: str = "blurb.md"
WWW_DIR_NAME: str = ".www"

SKIP_DIR_NAMES: frozenset[str] = frozenset(
    {
        ".git",
        ".venv",
        "venv",
        "env",
        "__pycache__",
        ".pytest_cache",
        "node_modules",
    }
)

PAGE_CANDIDATES: Sequence[str] = ("README.md", "BOOKMARK.md", "SKILL.md")


def iter_blurb_dirs(root: Path) -> Iterator[Path]:
    """Yield directories that contain .www/blurb.md, in sorted path order."""
    blurbs: List[Path] = []
    for path in root.rglob(BLURB_NAME):
        if not path.is_file():
            continue
        if path.parent.name != WWW_DIR_NAME:
            continue
        if any(part in SKIP_DIR_NAMES for part in path.relative_to(root).parts):
            continue
        blurbs.append(path.parent.parent)
    for directory in sorted(set(blurbs), key=lambda p: p.relative_to(root).as_posix()):
        yield directory


def depth_from_root(directory: Path, root: Path) -> int:
    """Return nesting depth (1 for immediate child of root)."""
    return len(directory.relative_to(root).parts)


def heading_for_depth(depth: int) -> str:
    """Return a markdown ATX heading prefix for the given depth."""
    level: int = min(depth + 1, 6)
    return "#" * level


def directory_page(directory: Path, root: Path) -> Optional[Path]:
    """Return the primary markdown page for a directory, if any."""
    for name in PAGE_CANDIDATES:
        candidate: Path = directory / name
        if candidate.is_file():
            return candidate
    pages: List[Path] = sorted(
        path for path in directory.glob("*.md") if path.is_file()
    )
    if pages:
        return pages[0]
    return None


def link_line(directory: Path, root: Path) -> str:
    """Build a markdown link line for the directory's primary page."""
    rel_dir: Path = directory.relative_to(root)
    label: str = rel_dir.as_posix()
    page: Optional[Path] = directory_page(directory, root)
    if page is None:
        return label
    rel_page: Path = page.relative_to(root)
    return f"[{label}]({rel_page.as_posix()})"


def blurb_body(directory: Path) -> str:
    """Return trimmed .www/blurb.md contents."""
    text: str = (directory / WWW_DIR_NAME / BLURB_NAME).read_text(encoding="utf-8")
    return text.strip()


def section_title(directory: Path, root: Path) -> str:
    """Return the display title for a blurb directory."""
    return directory.relative_to(root).as_posix()


def render_readme(root: Path) -> str:
    """Render README.md from all .www/blurb.md files under root."""
    lines: List[str] = [
        "# utils",
        "",
        "<!-- Generated by `make index` from `**/.www/blurb.md`. Do not edit the project",
        "     catalog by hand. Agent operating notes: [AGENTS.md](AGENTS.md).  -->",
        "",
    ]
    for directory in iter_blurb_dirs(root):
        depth: int = depth_from_root(directory, root)
        title: str = section_title(directory, root)
        lines.append(f"{heading_for_depth(depth)} {title}")
        lines.append("")
        lines.append(link_line(directory, root))
        lines.append("")
        body: str = blurb_body(directory)
        if body:
            lines.append(body)
            lines.append("")
    lines.extend(
        [
            "## License",
            "",
            "Copyright (c) 2010-2026 Johan Ovlinger",
            "",
            "This repository is licensed under the MIT License -- see [LICENSE](LICENSE).",
            "Unless a file or subdirectory states otherwise, the MIT License applies to",
            "all files in this repository.",
            "",
        ]
    )
    return "\n".join(lines)


def main(argv: Sequence[str]) -> int:
    """Write README.md and report the output path."""
    output: Path = Path(argv[1]).resolve() if len(argv) > 1 else README_PATH
    root: Path = output.parent
    output.write_text(render_readme(root), encoding="utf-8")
    print(output)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
