#!/usr/bin/env python3
"""Build utils/INDEX.md from nested .blurb.md files."""

from __future__ import annotations

import sys
from pathlib import Path
from typing import Iterator, List, Optional, Sequence

UTILS_ROOT: Path = Path(__file__).resolve().parent.parent
INDEX_PATH: Path = UTILS_ROOT / "INDEX.md"

SKIP_DIR_NAMES: frozenset[str] = frozenset(
    {
        ".git",
        ".venv",
        "venv",
        "env",
        "__pycache__",
        ".pytest_cache",
        "node_modules",
    }
)

PAGE_CANDIDATES: Sequence[str] = ("README.md", "BOOKMARK.md", "SKILL.md")


def iter_blurb_dirs(root: Path) -> Iterator[Path]:
    """Yield directories that contain .blurb.md, in sorted path order."""
    blurbs: List[Path] = []
    for path in root.rglob(".blurb.md"):
        if not path.is_file():
            continue
        if any(part in SKIP_DIR_NAMES for part in path.relative_to(root).parts):
            continue
        blurbs.append(path.parent)
    for directory in sorted(set(blurbs), key=lambda p: p.relative_to(root).as_posix()):
        yield directory


def depth_from_root(directory: Path, root: Path) -> int:
    """Return nesting depth (1 for immediate child of root)."""
    return len(directory.relative_to(root).parts)


def heading_for_depth(depth: int) -> str:
    """Return a markdown ATX heading prefix for the given depth."""
    level: int = min(depth + 1, 6)
    return "#" * level


def directory_page(directory: Path, root: Path) -> Optional[Path]:
    """Return the primary markdown page for a directory, if any."""
    for name in PAGE_CANDIDATES:
        candidate: Path = directory / name
        if candidate.is_file():
            return candidate
    pages: List[Path] = sorted(
        path
        for path in directory.glob("*.md")
        if path.name != ".blurb.md" and path.is_file()
    )
    if pages:
        return pages[0]
    return None


def link_line(directory: Path, root: Path) -> str:
    """Build a markdown link line for the directory's primary page."""
    rel_dir: Path = directory.relative_to(root)
    label: str = rel_dir.as_posix()
    page: Optional[Path] = directory_page(directory, root)
    if page is None:
        return label
    rel_page: Path = page.relative_to(root)
    return f"[{label}]({rel_page.as_posix()})"


def blurb_body(directory: Path) -> str:
    """Return trimmed blurb.md contents."""
    text: str = (directory / ".blurb.md").read_text(encoding="utf-8")
    return text.strip()


def section_title(directory: Path, root: Path) -> str:
    """Return the display title for a blurb directory."""
    return directory.relative_to(root).as_posix()


def render_index(root: Path) -> str:
    """Render INDEX.md from all .blurb.md files under root."""
    lines: List[str] = [
        "# Index",
        "",
        "Generated by `make index`. Do not edit by hand.",
        "",
    ]
    for directory in iter_blurb_dirs(root):
        depth: int = depth_from_root(directory, root)
        title: str = section_title(directory, root)
        lines.append(f"{heading_for_depth(depth)} {title}")
        lines.append("")
        lines.append(link_line(directory, root))
        lines.append("")
        body: str = blurb_body(directory)
        if body:
            lines.append(body)
            lines.append("")
    while lines and lines[-1] == "":
        lines.pop()
    lines.append("")
    return "\n".join(lines)


def main(argv: Sequence[str]) -> int:
    """Write INDEX.md and report the output path."""
    output: Path = Path(argv[1]).resolve() if len(argv) > 1 else INDEX_PATH
    root: Path = output.parent
    output.write_text(render_index(root), encoding="utf-8")
    print(output)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
