# Conductive-filament print profile.

include common

# 0.72 * (0.72 / 0.88)
trace_width_frac = 0.5890909090909091
adjacent_isolation_gap_frac = 0.12
isol_lig_frac = 0.18

# 1.10 * 0.66 * 1.50
pin_hole_diameter_mm = 1.089
device_hole_diameter_mm = 1.10
